stages:
  - build
  - deploy

build-code-job:
  stage: build
  image: node:18-buster
  script:
    - npm init -y
    - npm i ava

deploy-code-job:
  stage: deploy
  image: node:18-buster
  variables:
    GITHUB_URL: https://github.com/NN1C0/express-hello-world.git
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval `ssh-agent -s`
    - ssh-add <(echo "$PRIVATE_SSH_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - git checkout main
    - git merge feature
    - git add remote github $GITHUB_URL
    - git push github main