stages:
  - build
  - deploy

build-code-job:
  stage: build
  tags:
    - docker
  image: node:18-buster
  script:
    - echo "Built success!"

deploy-code-job:
  stage: deploy
  image: node:18-buster
  tags:
    - docker
  variables:
    GITHUB_URL: "git@github.com:NN1C0/express-hello-world.git"
    GITLAB_URL: "git@git.nexed.com:nicomeier/ci-cd.git"
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval `ssh-agent -s`
    - ssh-add <(echo "$PRIVATE_SSH_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa git.nexed.com >> ~/.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - git config --global user.email "nicomeier3@live.de"
    - git config --global user.name "Nico Meier"
    - git clone $GITLAB_URL
    - git remote rm github
    - git remote add $GITHUB_URL
    - git checkout main
    - git merge origin/feature
    #- git remote add github $GITHUB_URL
    - git push github